
version: 2

models:
# Core
  - name: dim_products
    description: Combines product info and aggregates order info to the product grain.

  - name: dim_users
    description: Combines user and location info.

  - name: fact_shipped_orders
    description: Promo info on orders that have been shipped or delivered.

# Marketing
  - name: int_orders
    description: Intermediate model that aggregates order info to the user grain.

  - name: fact_user_orders
    description: Fact model for user address, contact, and aggregated order info.

# Product
  - name: fact_page_view
    description: Event info for product views and order.